---
title: "French Polling"
author: "Shivi & Dasha"
date: "March 12, 2019"
output: html_document
---

```{r setup, include=FALSE}
# Let's all work on Spain.

# Read in the data automatically rather than rely on the download.

# Only want to use polling data from firms with at least 40 polls.

# Only want last year.

# Only 5 parties.


knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)

library(devtools)
#devtools::install_github("kjhealy/socviz")

x <- read_csv("https://pollofpolls.eu/get/polls/ES-parliament/format/csv")
```

```{r polling}
# Make a list of firms with at least 40 polls

good_firms <- x %>% 
  group_by(firm) %>% 
  summarize(number = n()) %>% 
  ungroup() %>% 
  filter(number >= 40) %>% 
  pull(firm)
  
# Figure out date a year ago
  
# Filter out data that we want to use and send it to the plot.

y <- x %>% 
  filter(firm %in% good_firms) %>% 
  filter(date > Sys.Date() - 365) %>%
  gather(key = "party", value = "poll", PP:PDeCAT)
  
#y %>% sample_n(10)

#y$date <- cut(y$date, breaks = "month")

#y$date = month(y$date)

y %>% filter(party %in% c("PSOE", "Cs", "PP", "Podemos", "VOX")) %>% 
  ggplot(aes(x = date, y = poll, color = party)) +
  geom_point() +
  geom_smooth(se = FALSE)


```